MIT WITH ROYALTY CLAUSE LICENSE

Copyright (c) 2025 John Paul Ruf

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, subject to the following conditions:

1. **Attribution**
   - The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

2. **Commercial Use Royalty**
   - If the Software, or any derivative works based on the Software, are used in any **commercial product or service** that generates **gross revenue of any kind**, the user must pay the original author, **John Paul Ruf**, a royalty equal to **1% of gross revenue** attributable to the use of the Software.
   - This includes, but is not limited to: sales of artwork generated by the Software, licensing fees, commissions, advertising revenue, subscriptions, and usage fees.

3. **Payment and Reporting**
   - Royalties must be paid on a **quarterly basis**, within 30 days of the end of each quarter.
   - Payments should be made via a method agreed upon with the author. Proof of revenue and payment history must be provided upon request.
   - Contact: [john.paul.ruf@gmail.com]

4. **Limitation of Liability**
   - THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY.

5. **Non-Compliance**
   - Failure to comply with the royalty terms constitutes a breach of this license, which immediately terminates the license to use the Software.

---

This license is a modified version of the MIT License with an additional commercial royalty clause. By using this Software, you agree to these terms.

